### ISSUE TITLE
search bug

### ISSUE THREAD

**Issue by listguy** [Yairderry/pre-course-2021-final-boilerplate#1]
When searching 'ss' in a todo item with text 'sss', todo item text changes.

**Step to reproduce** 
1. Add a ticket with todo text 'sss'
2. Search 'ss'

**Expected result:**
All occurrences of 'ss' highlighted in yellow

**Actual Result:**
Todo item text changed to 'sssss'

**Comment by Yairderry** [comment]
hi @listguy ! thank you for the issue, i'm, working on it.

**Comment by Yairderry** [comment]
hi @listguy , done.
